-- 057_permission_flags.sql
-- Supervision queue. Flags are generated by the nightly aggregation job when
-- rolling signal patterns cross configured thresholds (see src/backend/config/screening.js).
-- action_taken and reviewer_id are set by an admin when resolving the flag.
-- No automated process may resolve a flag with action_taken='revocation' without a reviewer_id.
-- signal_type values: low_feedback | confidence_declines | moderation_intervention | unprepared_reflections

CREATE TABLE permission_flags (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_id UUID NOT NULL REFERENCES permissions(id),
  signal_type   VARCHAR(100) NOT NULL,
  signal_data   JSONB,
  flagged_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at   TIMESTAMPTZ,
  reviewer_id   UUID REFERENCES users(id),
  action_taken  VARCHAR(50)
                  CHECK (action_taken IN (
                    'no_action',
                    'refresher_recommended',
                    'refresher_required',
                    'temporary_suspension',
                    'revocation'
                  )),
  resolved      BOOLEAN NOT NULL DEFAULT false,
  -- Revocation action requires a named reviewer.
  CONSTRAINT flag_revocation_requires_reviewer
    CHECK (action_taken != 'revocation' OR reviewer_id IS NOT NULL)
);

CREATE INDEX idx_permission_flags_queue       ON permission_flags(resolved, flagged_at DESC);
CREATE INDEX idx_permission_flags_user_perm   ON permission_flags(user_id, permission_id);
CREATE INDEX idx_permission_flags_reviewer    ON permission_flags(reviewer_id);

ALTER TABLE permission_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY deny_anon_permission_flags_read  ON permission_flags FOR SELECT TO anon USING (false);
CREATE POLICY deny_anon_permission_flags_write ON permission_flags FOR ALL    TO anon USING (false);
