ALTER TABLE therapist_profiles
  DROP CONSTRAINT IF EXISTS chk_therapist_session_formats,
  ADD COLUMN IF NOT EXISTS specializations TEXT[] NOT NULL DEFAULT '{}',
  DROP COLUMN IF EXISTS gender,
  DROP COLUMN IF EXISTS age,
  DROP COLUMN IF EXISTS rate_per_session_kes,
  DROP COLUMN IF EXISTS is_verified,
  DROP COLUMN IF EXISTS average_rating,
  DROP COLUMN IF EXISTS total_ratings_count,
  DROP COLUMN IF EXISTS total_sessions,
  DROP COLUMN IF EXISTS no_show_count,
  DROP COLUMN IF EXISTS kcpa_level,
  DROP COLUMN IF EXISTS kcpa_verified_at,
  DROP COLUMN IF EXISTS registration_number,
  DROP COLUMN IF EXISTS kmpdc_number,
  DROP COLUMN IF EXISTS indemnity_verified,
  DROP COLUMN IF EXISTS good_conduct_verified,
  DROP COLUMN IF EXISTS good_conduct_expires_at,
  DROP COLUMN IF EXISTS teletherapy_agreement_signed_at,
  DROP COLUMN IF EXISTS credentials_verified_by,
  DROP COLUMN IF EXISTS credentials_verified_at,
  DROP COLUMN IF EXISTS mpesa_number,
  DROP COLUMN IF EXISTS agreement_signed_at,
  DROP COLUMN IF EXISTS suspended,
  DROP COLUMN IF EXISTS category_ids;
